config/routes.rb
Rails.application.routes.draw do
  
  root "stocks#index"

  resources :stocks do
    collection do
      get 'balance'
      get 'history'
      get 'holding'
    end
  end

  resources :stocks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  def balance
    # code for balance
    @balances_parsed = AccountInfoManager::BalanceCaller.call
    puts "Balances are : #{@balances_parsed}"
  end

  def history
    #code for history
    @history_parsed = AccountInfoManager::HistoryCaller.call
    puts "History is : #{@history_parsed}"
  end

  def holding
    #code for holding
    @holdings_parsed = AccountInfoManager::HoldingCaller.call
    puts "Balances are : #{@holdings_parsed}"
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.fetch(:stock, {})
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyInvest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= link_to "Home", root_path %></p>
    <%= yield %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/balance.html.erb
<h1>Balances</h1>

<% balance = @balances_parsed['response']['accountbalance']%>
  <table>
    <thead>
      <tr>
        <th>account</th>
        <th>accountvalue</th>
        <th>cashavailableforwithdrawl</th>
        <th>daytrading</th>
        <th>equitypercentage</th>
        <th>options</th>
        <th>soddaytrading</th>
        <th>sodoptions</th>
        <th>sodstocks</th>
        <th>stock</th>
        <th>fedcall</th>
        <th>housecall</th>
        <th>accruedinterest</th>
        <th>cash</th>
        <th>cashavailable</th>
        <th>marginbalance</th>
        <th>mmf</th>
        <th>total</th>
        <th>uncleareddeposits</th>
        <th>unsettledfunds</th>
        <th>yield</th>
        <th>longoptions</th>
        <th>longstocks</th>
        <th>options</th>
        <th>shortoptions</th>
        <th>shortstocks</th>
        <th>stocks</th>
        <th>total</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= balance['account'] %> </td>
        <td> <%= balance['accountvalue'] %> </td>
        <td> <%= balance['buyingpower']['cashavailableforwithdrawal']%> </td>
        <td> <%= balance['buyingpower']['daytrading']%> </td>
        <td> <%= balance['buyingpower']['equitypercentage']%> </td>
        <td> <%= balance['buyingpower']['options']%> </td>
        <td> <%= balance['buyingpower']['soddaytrading']%> </td>
        <td> <%= balance['buyingpower']['sodoptions']%> </td>
        <td> <%= balance['buyingpower']['sodstock']%> </td>
        <td> <%= balance['buyingpower']['stock']%> </td>
        <td> <%= balance['fedcall'] %> </td>
        <td> <%= balance['housecall'] %> </td>

        <td> <%= balance['money']['accruedinterest']%> </td>
        <td> <%= balance['money']['cash']%> </td>
        <td> <%= balance['money']['cashavailable']%> </td>
        <td> <%= balance['money']['marginbalance']%> </td>
        <td> <%= balance['money']['mmf']%> </td>
        <td> <%= balance['money']['total']%> </td>
        <td> <%= balance['money']['uncleareddeposits']%> </td>
        <td> <%= balance['money']['unsettledfunds']%> </td>
        <td> <%= balance['money']['yield']%> </td>

        <td> <%= balance['securities']['longoptions']%> </td>
        <td> <%= balance['securities']['longstocks']%> </td>
        <td> <%= balance['securities']['options']%> </td>
        <td> <%= balance['securities']['shortoptions']%> </td>
        <td> <%= balance['securities']['shortstocks']%> </td>
        <td> <%= balance['securities']['stocks']%> </td>
        <td> <%= balance['securities']['total']%> </td>

      </tr>
    </tbody>
  </table>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/history.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>
<% @new_hash = {} %>

<% @history_parsed["response"]["transactions"]["transaction"].each do |transaction| %>

<table>
  <thead>
    <tr>
      <th>activity</th>
      <th>amount</th>
      <th>date</th>
      <th>desc</th>
      <th>symbol</th>
      <th>accounttype</th>
      <th>commission</th>
      <th>description</th>
      <th>fee</th>
      <th>price</th>
      <th>quantity</th>
      <th>secfee</th>
      <th>security</th>
      <th>cusip</th>
      <th>id</th>
      <th>sectyp</th>
      <th>sym</th>
      <th>settlementdate</th>
      <th>side</th>
      <th>source</th>
      <th>tradedate</th>
      <th>transactionid</th>
      <th>transactiontype</th>

    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= transaction['activity']%></td>
      <td><%= transaction['amount']%></td>
      <td><%= transaction['date']%></td>
      <td><%= transaction['desc']%></td>
      <td><%= transaction['symbol']%></td>
      <td><%= transaction['transaction']['accounttype']%></td>
      <td><%= transaction['transaction']['commission']%></td>
      <td><%= transaction['transaction']['description']%></td>
      <td><%= transaction['transaction']['fee']%></td>
      <td><%= transaction['transaction']['price']%></td>
      <td><%= transaction['transaction']['quantity']%></td>
      <td><%= transaction['transaction']['secfee']%></td>
      <td><%= transaction['transaction']['security']['cusip']%></td>
      <td><%= transaction['transaction']['security']['id']%></td>
      <td><%= transaction['transaction']['security']['sectyp']%></td>
      <td><%= transaction['transaction']['security']['sym']%></td>
      <td><%= transaction['settlementdate']%></td>
      <td><%= transaction['side']%></td>
      <td><%= transaction['source']%></td>
      <td><%= transaction['tradedate']%></td>
      <td><%= transaction['transactionid']%></td>
      <td><%= transaction['transactiontype']%></td>
    </tr>
  </tbody>
</table>

<% end %>

app/views/stocks/holding.html.erb
<p id="notice"><%= notice %></p>

<% @new_hash = {} %>

<h1>Holdings</h1>
<% @holdings_parsed["response"]["accountholdings"]["holding"].each do |holding| %>
<% @new_hash["#{holding["instrument"]["sym"]}"] = holding %>
<table>
  
  <thead>
    <tr>
      <th>
        sym
      </th>
      <th>
        accounttype
      </th>
      <th>
        costbasis
      </th>
      <th>
        gainloss
      </th>
      <th>
        cfi
      </th>
      <th>
        cusip
      </th>
      <th>
        desc
      </th>
      <th>
        factor
      </th>
      <th>
        matdt
      </th>
      <th>
        mmy
      </th>
      <th>
        mult
      </th>
      <th>
        putcall
      </th>
      <th>
        sectyp
      </th>
      <th>
        strkpx
      </th>
      <th>
        marketvalue
      </th>
      <th>
        marketvaluechange
      </th>
      <th>
        price
      </th>
      <th>
        purchaseprice
      </th>
      <th>
        qty
      </th>
      <th>
        change
      </th>
      <th>
        dividenddata
      </th>
      <th>
        format
      </th>
      <th>
        lastprice
      </th>
      <th>
        sodcostbasis
      </th>
      <th>
        underlying
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td>
      <%= holding["instrument"]["sym"] %>
    </td>
    <td>
      <%= holding["accounttype"] %>
    </td>
    <td>
      <%= holding["costbasis"] %>
    </td>
    <td>
      <%= holding["gainloss"] %>
    </td>
    <td>
      <%= holding["instrument"]["cfi"] %>
    </td>
    <td>
      <%= holding["instrument"]["cusip"] %>
    </td>
    <td>
      <%= holding["instrument"]["desc"] %>
    </td>
    <td>
      <%= holding["instrument"]["factor"] %>
    </td>
    <td>
      <%= holding["instrument"]["matdt"] %>
    </td>
    <td>
      <%= holding["instrument"]["mmy"] %>
    </td>
    <td>
      <%= holding["instrument"]["mult"] %>
    </td>
    <td>
      <%= holding["instrument"]["putcall"] %>
    </td>
    <td>
      <%= holding["instrument"]["sectyp"] %>
    </td>
    <td>
      <%= holding["instrument"]["strkpx"] %>
    </td>

    <td>
      <%= holding["marketvalue"] %>
    </td>
    <td>
      <%= holding["marketvaluechange"] %>
    </td>
    <td>
      <%= holding["price"] %>
    </td>
    <td>
      <%= holding["purchaseprice"] %>
    </td>
    <td>
      <%= holding["qty"] %>
    </td>
    <td>
      <%= holding["quote"]["change"] %>
    </td>
    <td>
      <%= holding["quote"]["extendedquote"]["dividenddata"] %>
    </td>
    <td>
      <%= holding["quote"]["format"] %>
    </td>
    <td>
      <%= holding["quote"]["lastprice"] %>
    </td>
    <td>
      <%= holding["sodcostbasis"] %>
    </td>
  </tr>
  </tbody>
</table>

<% end %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>
<h3><%= link_to "Balances", balance_stocks_path %>| <%= link_to "Holdings", holding_stocks_path %> | <%= link_to "History", history_stocks_path %> </h3>
<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>